[pytest]

addopts =
    --headed
    --browser chromium
    --slowmo 2000
    --html=reports/report.html
    --self-contained-html
    --alluredir=allure-results

testpaths = tests
python_files = test_*.py
